type ScorecardEntry {
  score: Int
  comments: String
}

input ScorecardEntryInput {
  score: Int!
  comments: String
}


type FarrowingBackendScorecard {
  area: Job!
  operator: Resource
  sows: ScorecardEntry!
  piglets: ScorecardEntry!
  feed: ScorecardEntry!
  water: ScorecardEntry!
  crate: ScorecardEntry!
  room: ScorecardEntry!
}


input PostFarrowingBackendScorecardInput {
  area: String!
  operator: String!
  sows: ScorecardEntryInput!
  piglets: ScorecardEntryInput!
  feed: ScorecardEntryInput!
  water: ScorecardEntryInput!
  crate: ScorecardEntryInput!
  room: ScorecardEntryInput!
}

input SaveFarrowingBackendScorecardInput {
  area: String!
  operator: String
  sows: ScorecardEntryInput
  piglets: ScorecardEntryInput
  feed: ScorecardEntryInput
  water: ScorecardEntryInput
  crate: ScorecardEntryInput
  room: ScorecardEntryInput
}

type FarrowingBackendScorecardResult {
  success: Boolean!
  scorecard: FarrowingBackendScorecard!
}

type NurseryFinisherScorecard {
  area: Job!
  operator: Resource
  sows: ScorecardEntry!
  piglets: ScorecardEntry!
  feed: ScorecardEntry!
  water: ScorecardEntry!
  crate: ScorecardEntry!
  room: ScorecardEntry!
}

input PostNurseryFinisherScorecardInput {
  area: String!
  operator: String!
  sows: ScorecardEntryInput!
  piglets: ScorecardEntryInput!
  feed: ScorecardEntryInput!
  water: ScorecardEntryInput!
  crate: ScorecardEntryInput!
  room: ScorecardEntryInput!
}

input SaveNurseryFinisherScorecardInput {
  area: String!
  operator: String
  sows: ScorecardEntryInput
  piglets: ScorecardEntryInput
  feed: ScorecardEntryInput
  water: ScorecardEntryInput
  crate: ScorecardEntryInput
  room: ScorecardEntryInput
}

type NurseryFinisherScorecardResult {
  success: Boolean!
  scorecard: FarrowingBackendScorecard!
}


input SetAreaOperatorInput {
  area: String!
  operator: String!
}

type SetAreaOperatorResult {
  success: Boolean!
  area: Job!
}



type Query {
  farrowingBackendScorecard(area: String!): FarrowingBackendScorecard
  farrowingBackendAreas: [Job!]!
  farrowingBackendArea(number: String!): Job
  farrowingBackendOperators: [Resource!]!
  nurseryFinisherScorecard(area: String!): NurseryFinisherScorecard
  nurseryFinisherAreas: [Job!]!
  nurseryFinisherArea(area: String!): Job
  nurseryFinisherOperators: [Resource!]!
}

type Mutation {
  setAreaOperator(input: SetAreaOperatorInput!): SetAreaOperatorResult!
  postFarrowingBackendScorecard(input: PostFarrowingBackendScorecardInput!): FarrowingBackendScorecardResult!
  saveFarrowingBackendScorecard(input: SaveFarrowingBackendScorecardInput!): FarrowingBackendScorecardResult!
  postNurseryFinisherScorecard(input: PostNurseryFinisherScorecardInput!): NurseryFinisherScorecardResult!
  saveNurseryFinisherScorecard(input: SaveNurseryFinisherScorecardInput!): NurseryFinisherScorecardResult!
}
