type ScorecardGroup {
  code: String!
  description: String!
}

type ScorecardElement {
  id: ID!
  label: String!
  code: String!
  order: Int!
}

type ScorecardPage {
  title: String
  elements: [ScorecardElement!]!
}

type ScorecardConfig {
  job: Job!
  pages: [ScorecardPage!]!
}

input ScorecardElementResponseInput {
  elementId: ID!
  numericValue: Float
  stringValue: String
}

input PostScorecardInput {
  job: String!
  data: [ScorecardElementResponseInput!]!
}

type ScorecardResult {
  success: Boolean!
  scorecard: Scorecard
}

type ScorecardElementResponse {
  elementId: ID!
  numericValue: Float
  stringValue: String
}

type Scorecard {
  job: Job!
  data: [ScorecardElementResponse!]!
}

type Query {
  scorecardGroups: [ScorecardGroup!]!
  scorecardConfig(job: String!): ScorecardConfig
  scorecard(job: String!): Scorecard
}

type Mutation {
  saveScorecard(input: PostScorecardInput!): ScorecardResult!
  postScorecard(input: PostScorecardInput!): ScorecardResult!
}
