query InventorySelect {
  jobs(input: {}) {
    number
    description
  }
  locations {
    code
    name
  }
  livestockActivityDefaults {
    job {
      number
    }
    location {
      code
    }
  }
}
