query InventoryItem($input: String!) {
  items(location: $input) {
    number
    location
    balance
    description
    type
    cost
    unit
  }
}
mutation PostInventory($input: PostInventoryInput!) {
  postInventory(input: $input) {
    success
  }
}
