type UserLocations {
  mode: InclusivityMode!
  list: [Location!]!
}

type User {
  username: String!
  license: String!
  name: String!
  locations: UserLocations!
}

input LoginInput {
  username: String!
  password: String!
}

type LoginResult {
  success: Boolean!
  user: User!
}

type LogoutResult {
  success: Boolean!
}

input UpdateUserLocationsInput {
  add: [String!]
  remove: [String!]
  mode: InclusivityMode
}

type UpdateUserLocationsResult {
  success: Boolean!
  locations: UserLocations!
}

type Query {
  user: User
  users: [User!]!
  locations: [Location!]!
}

type Mutation {
  login(input: LoginInput!): LoginResult!
  logout: LogoutResult!

  updateUserLocations(input: UpdateUserLocationsInput!): UpdateUserLocationsResult!
}
