fragment PigPurchaseFragment on PigPurchase {
  event {
    code
  }
  job {
    number
    description
    inventory
    deadQuantity
  }  
  quantity
  smallPigQuantity
  totalWeight
  comments
}

query PigPurchase($job: String!) {
  pigPurchaseEventTypes {
    code
    description
  }
  pigPurchase(job: $job) {
    ...PigPurchaseFragment
  }
}

mutation SavePigPurchase($input: SavePigPurchaseInput!) {
  savePigPurchase(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigPurchase {
      ...PigPurchaseFragment
    }
  }
}

mutation PostPigPurchase($input: PostPigPurchaseInput!) {
  postPigPurchase(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigPurchase {
      ...PigPurchaseFragment
    }
  }
}
