fragment PigActivityDefaultsFragment on PigActivityDefaults {
  job {
    number
  }
  prices {
    animal
    price
  }
}

query PigActivityJobs {
  pigActivityDefaults {
    job {
      number
    }
  }
  itemJournalTemplates {
    name
    description
    type
    reasonCode
    sourceCode
  }
  pigActivityJobs {
    number
    description
    inventory
    deadQuantity
  }
}
