fragment PigPurchaseFragment on PigPurchase {
  animal
  job {
    number
    description
    inventory
    deadQuantity
  }  
  quantity
  totalWeight
  price
  comments
}

query PigPurchase($job: String!) {
  pigTypes {
    number
    description
  }
  pigActivityDefaults {
    pigList {
      pigType
      price
    }
  }
  pigPurchase(job: $job) {
    ...PigPurchaseFragment
  }
}

mutation SavePigPurchase($input: SavePigPurchaseInput!) {
  savePigPurchase(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigPurchase {
      ...PigPurchaseFragment
    }
  }
}

mutation PostPigPurchase($input: PostPigPurchaseInput!) {
  postPigPurchase(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigPurchase {
      ...PigPurchaseFragment
    }
  }
}
