fragment PigAdjustmentFragment on PigAdjustment {
 event {
   code
 }
 job {
    number
    description
    inventory
    deadQuantity
  }
  postingDate
  quantity
  totalWeight
  comments
  imagesUID
}

query PigAdjustment($job: String!) {
  pigAdjustmentEventTypes {
    code
    description
  }
  pigAdjustment(job: $job) {
    ...PigAdjustmentFragment
  }
}

mutation SavePigAdjustment($input: SavePigAdjustmentInput!) {
  savePigAdjustment(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigAdjustment {
      ...PigAdjustmentFragment
    }
  }
}

mutation PostPigAdjustment($input: PostPigAdjustmentInput!) {
  postPigAdjustment(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigAdjustment {
      ...PigAdjustmentFragment
    }
  }
}
