fragment PigMortalityFragment on PigMortality {
  event {
    code
  }
  job {
    number
    description
    inventory
    deadQuantity
  }  
  quantities {
    code
    quantity
  }
  postingDate
  comments
}

query PigMortality($job: String!) {
  pigMortalityEventTypes {
    code
    description
    reasons {
      code
      description
    }
  }
  pigMortality(job: $job) {
    ...PigMortalityFragment
  }
}

mutation SavePigMortality($input: SavePigMortalityInput!) {
  savePigMortality(input: $input) {
    pigMortality {
      ...PigMortalityFragment
    }
  }
}

mutation PostPigMortality($input: PostPigMortalityInput!) {
  postPigMortality(input: $input) {
    pigMortality {
      ...PigMortalityFragment
    }
  }
}
