fragment PigGradeOffFragment on PigGradeOff {
  animal
  job {
    number
    description
    inventory
    deadQuantity
  }  
  quantities {
    code
    quantity
  }
  pigWeight
  comments
}

query PigGradeOff($job: String!) {
  pigTypes {
    number
    description
  }
  pigGradeOffReasons {
    code
    description
  }
  pigGradeOff(job: $job) {
    ...PigGradeOffFragment
  }
}

mutation SavePigGradeOff($input: SavePigGradeOffInput!) {
  savePigGradeOff(input: $input) {
    pigGradeOff {
      ...PigGradeOffFragment
    }
  }
}

mutation PostPigGradeOff($input: PostPigGradeOffInput!) {
  postPigGradeOff(input: $input) {
    pigGradeOff {
      ...PigGradeOffFragment
    }
  }
}

