fragment PigActivityDefaultsFragment on PigActivityDefaults {
  job {
    number
  }
  pigList {
    pigType
    price
  }
}

query PigActivityJobs {
  pigActivityDefaults {
    job {
      number
    }
  }
  pigActivityJobs {
    number
    description
    inventory
    deadQuantity
  }
}