fragment PigGradeOffFragment on PigGradeOff {
  animal
  job {
    number
    description
    inventory
    deadQuantity
  }  
  lameQuantity
  respitoryQuantity
  bellyRuptureQuantity
  scrotumRuptureQuantity
  scoursQuantity
  smallQuantity
  unthriftyQuantity
  pigWeight
  comments
}

query PigGradeOff($job: String!) {
  pigTypes {
    number
    description
  }
  pigGradeOff(job: $job) {
    ...PigGradeOffFragment
  }
}

mutation SavePigGradeOff($input: SavePigGradeOffInput!) {
  savePigGradeOff(input: $input) {
    pigGradeOff {
      ...PigGradeOffFragment
    }
  }
}

mutation PostPigGradeOff($input: PostPigGradeOffInput!) {
  postPigGradeOff(input: $input) {
    pigGradeOff {
      ...PigGradeOffFragment
    }
  }
}

