fragment PigMoveFragment on PigMove {
  event {
    code
  }
  fromJob {
    number
    description
    inventory
    deadQuantity
  }
  toJob {
    number
  }
  quantity
  smallPigQuantity
  totalWeight
  comments
}

query PigMove($job: String!) {
  pigMoveEventTypes {
    code
    description
  }
  pigActivityJobs {
    number
    description
  }
  pigMove(job: $job) {
    ...PigMoveFragment
  }
}

mutation SavePigMove($input: SavePigMoveInput!) {
  savePigMove(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigMove {
      ...PigMoveFragment
    }
  }
}

mutation PostPigMove($input: PostPigMoveInput!) {
  postPigMove(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigMove {
      ...PigMoveFragment
    }
  }
}
