fragment PigWeanFragment on PigWean {
  animal
  event {
    code
  }
  job {
    number
    description
    inventory
    deadQuantity
  }  
  quantity
  smallPigQuantity
  totalWeight
  price
  comments
}

query PigWean($job: String!) {
  pigWeanEventTypes {
    code
    description
  }
  animals {
    number
    description
  }
  pigActivityDefaults {
    prices {
      animal
      price
    }
  }
  pigWean(job: $job) {
    ...PigWeanFragment
  }
}

mutation SavePigWean($input: SavePigWeanInput!) {
  savePigWean(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigWean {
      ...PigWeanFragment
    }
  }
}

mutation PostPigWean($input: PostPigWeanInput!) {
  postPigWean(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigWean {
      ...PigWeanFragment
    }
  }
}
