fragment PigMortalityFragment on PigMortality {
  animal
  job {
    number
    description
    inventory
    deadQuantity
  }  
  naturalQuantity
  euthanizedQuantity
  comments
}

query PigMortality($job: String!) {
  animals {
    number
    description
  }
  pigMortality(job: $job) {
    ...PigMortalityFragment
  }
}

mutation SavePigMortality($input: SavePigMortalityInput!) {
  savePigMortality(input: $input) {
    pigMortality {
      ...PigMortalityFragment
    }
  }
}

mutation PostPigMortality($input: PostPigMortalityInput!) {
  postPigMortality(input: $input) {
    pigMortality {
      ...PigMortalityFragment
    }
  }
}
