enum InclusivityMode {
  INCLUDE
  EXCLUDE
}

type Job {
  number: String!
  description: String!
  personResponsible: Resource!
  inventory: Int
  deadQuantity: Int
  startDate: String
  groupStartDate: String
  location: Location!
  projectManager: User
}

type Item {
  number: String!
  description: String!
  cost: Int
}

type Reason {
  code: String!
  description: String!
}

type Resource {
  number: String!
  name: String!
  unitPrice: Float
}

type Location {
  code: String!
  name: String!
}

input JobFilter {
  groups: [String!]
  locations: [String!]
}

input ResourceFilter {
  group: String
  type: String
}

type Query {
  resources(input: ResourceFilter): [Resource!]!
  resource(code: String!): Resource
  jobs(input: JobFilter): [Job!]!
  job(number: String!): Job
  item(number: String!): Item
}

