enum InclusivityMode {
  INCLUDE
  EXCLUDE
}

type Job {
  number: String!
  description: String!
  personResponsible: Resource!
  inventory: Int
  deadQuantity: Int
  location: Location!
}

type Item {
  number: String!
  description: String!
}

type Reason {
  code: String!
  description: String!
}

type Resource {
  number: String!
  name: String!
}

type Location {
  code: String!
  name: String!
}

input JobFilter {
  groups: [String!]
  locations: [String!]
}

input ResourceFilter {
  group: String
  type: String
}

type Query {
  resources(input: ResourceFilter): [Resource!]!
  resource(code: String!): Resource
  jobs(input: JobFilter): [Job!]!
  job(number: String!): Job
}

