fragment UserLocationsFields on UserLocations {
  mode
  list {
    code
    name
  }
}

query Locations {
  locations {
    code
    name
  }
  user {
    username
    locations {
      ...UserLocationsFields
    }
  }
}

mutation UpdateLocations($input: UpdateUserLocationsInput!) {
  updateUserLocations(input: $input) {
    locations {
      ...UserLocationsFields
    }
  }
}