fragment LivestockActivityDefaultsFragment on LivestockActivityDefaults {
  job {
    number
  }
  prices {
    animal
    price
  }
}

query LivestockActivityJobs($isShipment: Boolean) {
  livestockActivityDefaults {
    job {
      number
    }
  }
  itemJournalTemplates {
    name
    description
    type
    reasonCode
    sourceCode
  }
  livestockActivityJobs(isShipment: $isShipment) {
    number
    description
    inventory
    deadQuantity
  }
}

mutation AutoPostItem($input: AutoPostInput!) {
  autoPostItemJournal(input: $input) {
    success
  }
}
