query MaintenanceAsset($number: String!) {
    maintenanceAsset(number: $number) {
        number
        description
    }
    maintenanceIntervals(assetNo: $number) {
      code
      interval
      unitType
      description
    }
    item(number: "LABOR") {
      number
      cost
    }
}

mutation PostMaintenance($input: PostMaintenanceInput!) {
  postMaintenance(input: $input) {
    success
  }
}