type FuelAsset {
    number: String!
    code: String!
    description: String!
    fuelType: String!
    fuelCost: Float!
}

input PostFuelInput {
    asset: String!
    postingDate: String
    gallons: Float!
    mileage: Float!
    comments: String
}

type FuelResult {
  success: Boolean!
}

type Query {
    fuelAsset(number: String!): FuelAsset
    fuelAssets: [FuelAsset!]!
}

type Mutation {
  postFuel(input: PostFuelInput!): FuelResult!
}
