fragment scorecardFields on Scorecard {
  job {
    number
  }
  data {
    elementId
    numericValue
    stringValue
  }
}

query ScorecardJobs {
  jobs(input: { groups: ["NURSGROWSITE"] }) {
    number
    description
  }
}

query ScorecardPigJobs($location: String!) {
  jobs(input: { groups: ["SOWS", "GDU", "MKT PIGS"], locations: [$location] }) {
    number
    description
  }
}

query ScorecardPeople {
  people: resources(input: { type: "Person" }) {
    number
    name
  }
}

query NurseryFinisherScorecard($job: String!) {
  job: job(number: $job) {
    number
    location {
      code
    }
    personResponsible {
      number
    }
  }
  scorecardPages(job: $job) {
    title
    elements {
      id
      label
      code
      order
    }
  },
  scorecard(job: $job) {
    ...scorecardFields
  }
}

mutation saveScorecard($input: SaveScorecardInput!) {
  saveScorecard(input: $input) {
    success
    scorecard {
      ...scorecardFields
    }
  }
}