fragment GrowFinishJobFields on Job {
  number
  description
}

query GrowFinishJobs {
  growFinishJobs {
    number
    description
  }
}

query PersonResponsible {
  personResponsible {
    name
    number
  }
}