fragment GrowFinishJobFields on Job {
  number
  description
}

fragment ScorecardFields on Scorecard {
  job {
    number
  }
  date
  operator {
    number
  }
}

query ScorecardJobs {
  jobs(input: { group: "NURSGROWSITE" }) {
    number
    description
  }
}

query PersonResponsible {
  personResponsible {
    name
    number
  }
}

query NurseryFinisherScorecard($job: String!) {
  job: job(number: $job) {
    number
    # what is the scorecard term for operator?
    personResponsible {
      name
      number
    }
  }
  # scorecardPages(job: $job) {
  #   # pages?
  # }
  # scorecardData(job: $job) {
  #   job {
  #     number
  #   }
  #   date
  #   operator
  #   # array of inputs
  # }
}

mutation saveScorecard($input: SaveScorecardInput!) {
  saveScorecard(input: $input) {
    success
    scorecard {
      ...ScorecardFields
    }
  }
}