fragment scorecardFields on Scorecard {
  job {
    number
  }
  data {
    elementId
    numericValue
    stringValue
  }
}

query ScorecardGroups {
  scorecardGroups {
    code
    description
  }
}

query ScorecardTargetTemp($code: String!) {
  resource(code: $code) {
    number
    name
    unitPrice
  }
}

query ScorecardPigJob($job: String!) {
  job(number: $job) {
    number
    description
    startDate
    groupStartDate
    deadQuantity
  }
}

query ScorecardJobs($group: String!) {
  jobs(input: { groups: [$group] }) {
    number
    description
  }
}

query ScorecardPigJobs($location: String!) {
  jobs(input: { groups: ["SOWS", "GDU", "MKT PIGS"], locations: [$location] }) {
    number
    description
  }
}

query ScorecardPeople {
  people: resources(input: { type: "Person" }) {
    number
    name
  }
}

query Scorecard($job: String!) {
  job: job(number: $job) {
    number
    location {
      code
    }
    personResponsible {
      number
    }
  }
  scorecardConfig(job: $job) {
    job {
      number
    }
    pages {
      title
      elements {
        id
        label
        code
        order
      }
    }
  },
  scorecard(job: $job) {
    ...scorecardFields
  }
}

mutation SaveScorecard($input: PostScorecardInput!) {
  saveScorecard(input: $input) {
    success
    scorecard {
      ...scorecardFields
    }
  }
}

mutation PostScorecard($input: PostScorecardInput!) {
  postScorecard(input: $input) {
    success
    scorecard {
      ...scorecardFields
    }
  }
}