fragment scorecardFields on Scorecard {
  job {
    number
  }
  data {
    elementId
    numericValue
    stringValue
  }
}

query ScorecardGroups {
  scorecardGroups {
    code
    description
  }
}

query ScorecardTargetTemp($code: String!) {
  resource(code: $code) {
    number
    name
    unitPrice
  }
}

query ScorecardLivestockJob($job: String!) {
  job(number: $job) {
    number
    description
    startDate
    groupStartDate
    deadQuantity
  }
}

query ScorecardJobs($group: String!) {
  jobs(input: { groups: [$group] }) {
    number
    description
  }
}

query ScorecardLivestockJobs($location: String!) {
  jobs(input: { groups: ["MKT PIGS"], locations: [$location] }) {
    number
    description
  }
}

query ScorecardPeople {
  people: resources(input: { type: "Person" }) {
    number
    name
  }
}

query ScorecardUsers {
  users {
    username
    name
  }
}

query Scorecard($job: String!) {
  job: job(number: $job) {
    number
    location {
      code
    }
    personResponsible {
      number
    }
    projectManager {
      username
    }
  }
  scorecardConfig(job: $job) {
    job {
      number
    }
    pages {
      title
      elements {
        id
        label
        code
        order
      }
    }
  },
  scorecard(job: $job) {
    ...scorecardFields
  }
}

mutation SaveScorecard($input: PostScorecardInput!) {
  saveScorecard(input: $input) {
    success
    scorecard {
      ...scorecardFields
    }
  }
}

mutation PostScorecard($input: PostScorecardInput!) {
  postScorecard(input: $input) {
    success
    scorecard {
      ...scorecardFields
    }
  }
}

mutation AutoPostScorecards($input: ScorecardAutoPostInput!) {
  autoPostScorecards(input: $input) {
    success
  }
}
