fragment PigAdjustmentFragment on PigAdjustment {
  animal
  job {
    number
    description
    inventory
    deadQuantity
  }  
  quantity
  weight
  price
  comments
}

query PigAdjustment($job: String!) {
  pigTypes {
    number
    description
  }
  pigActivityDefaults {
    price
  }
  pigAdjustment(job: $job) {
    ...PigAdjustmentFragment
  }
}

mutation SavePigAdjustment($input: SavePigAdjustmentInput!) {
  savePigAdjustment(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigAdjustment {
      ...PigAdjustmentFragment
    }
  }
}

mutation PostPigAdjustment($input: PostPigAdjustmentInput!) {
  postPigAdjustment(input: $input) {
    defaults {
      ...PigActivityDefaultsFragment
    }
    pigAdjustment {
      ...PigAdjustmentFragment
    }
  }
}
