fragment PigActivityDefaultsFragment on PigActivityDefaults {
  job {
    number
  }
  price
}

fragment PostPigActivityResultFragment on PostPigActivityResult {
  defaults {
    ...PigActivityDefaultsFragment
  }
}

query PigActivity {
  pigActivityJobs {
    number
    description
  }
  pigActivityDefaults {
    ...PigActivityDefaultsFragment
  }
}

mutation PostPigMove($input: PigMoveInput!) {
  postPigMove(input: $input) {
    ...PostPigActivityResultFragment
  }
}

mutation PostPigAdjustment($input: PigAdjustmentInput!) {
  postPigAdjustment(input: $input) {
    ...PostPigActivityResultFragment
  }
}

mutation PostPigGradeOff($input: PigGradeOffInput!) {
  postPigGradeOff(input: $input) {
    ...PostPigActivityResultFragment
  }
}

mutation PostPigWean($input: PigWeanInput!) {
  postPigWean(input: $input) {
    ...PostPigActivityResultFragment
  }
}

mutation PostPigPurchase($input: PigPurchaseInput!) {
  postPigPurchase(input: $input) {
    ...PostPigActivityResultFragment
  }
}

mutation PostPigMortality($input: PigMortalityInput!) {
  postPigMortality(input: $input) {
    ...PostPigActivityResultFragment
  }
}