fragment FarrowingBackendAreaFields on Job {
  number
  description
  personResponsible {
    name
    number
  }
}

fragment FarrowingBackendScorecardFields on FarrowingBackendScorecard {
  area {
    number
  }
  operator {
    number
  }
  sows {
    score
    comments
  }
  piglets {
    score
    comments
  }
  feed {
    score
    comments
  }
  water {
    score
    comments
  }
  crate {
    score
    comments
  }
  room {
    score
    comments
  }
}

query FarrowingBackendScorecardAreas {
  areas: farrowingBackendAreas {
    number
    description
  }
}

query FarrowingBackendScorecard($area: String!) {
  area: farrowingBackendArea(number: $area) {
    number
    description
    personResponsible {
      number
    }
  }
  operators: farrowingBackendOperators {
    number
    name
  }
  scorecard: farrowingBackendScorecard(area: $area) {
    ...FarrowingBackendScorecardFields 
  }
}

query FarrowingBackendOperators($area: String!) {
  area: farrowingBackendArea(number: $area) {
    ...FarrowingBackendAreaFields
  }
  operators: farrowingBackendOperators {
    number
    name
  }
}

mutation PostFarrowingBackendScorecard($input: PostFarrowingBackendScorecardInput!) {
  postFarrowingBackendScorecard(input: $input) {
    success
    scorecard {
      ...FarrowingBackendScorecardFields 
    }
  }
}

mutation SaveFarrowingBackendScorecard($input: SaveFarrowingBackendScorecardInput!) {
  saveFarrowingBackendScorecard(input: $input) {
    success
    scorecard {
      ...FarrowingBackendScorecardFields 
    }
  }
}

mutation SetAreaOperator($input: SetAreaOperatorInput!) {
  setAreaOperator(input: $input) {
    area {
      ...FarrowingBackendAreaFields
    }
  }
}