query FarrowingBackendScorecard {
  farrowingBackendAreas {
    number
    description
    personResponsible {
      name
      number
    }
  }
}

query FarrowingBackendOperators {
  farrowingBackendOperators {
    name
    number
  }
}

mutation PostFarrowingBackendScorecard($input: FarrowingBackendScorecardInput!) {
  postFarrowingBackendScorecard(input: $input) {
    success
  }
}