query FarrowingBackendScorecard {
  areas: farrowingBackendAreas {
    number
    description
    personResponsible {
      name
      number
    }
  }
  operators: farrowingBackendOperators {
    number
    name
  }
}

mutation PostFarrowingBackendScorecard($input: FarrowingBackendScorecardInput!) {
  postFarrowingBackendScorecard(input: $input) {
    success
  }
}