fragment UserParts on User {
  username
  name
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    user {
      ...UserParts
    }
  }
}

query User {
  user {
    ...UserParts
  }
}

mutation Logout {
  logout {
    success
  }
}
