type MaintenanceAsset {
  number: String!
  description: String
  classCode: String
  code: String!
  interval: Int
  unitType: String
  maintenanceDesc: String
}

type MaintenanceHistoryAsset {
  entry: Int!
  number: String!
  amount: Float!
  maintenanceCode: String!
  reasonCode: String!
  postingDate: String!
  quantity: Int!
  description: String!
  meta: Int!
}

input PostMaintenanceInput {
  asset: String!
  postingDate: String
  type: String!
  mileage: Float
  workHours: Float!
  totalCost: Float
  comments: String
}

type MaintenanceResult {
  success: Boolean!
}

type Query {
  maintenanceAsset(number: String!): MaintenanceAsset
  maintenanceHistoryAsset(number: String!): [MaintenanceHistoryAsset!]!
  maintenanceAssets: [MaintenanceAsset!]!
  maintenanceAssetsByNo(assetNo: String!): [MaintenanceAsset!]!
}

type Mutation {
  postMaintenance(input: PostMaintenanceInput!): MaintenanceResult!
}
