type MaintenanceAsset {
  number: String!
  description: String
  classCode: String
  code: String!
  interval: Int
  unitType: String
  maintenanceDesc: String
}

input PostMaintenanceInput {
  asset: String!
  postingDate: String
  type: String!
  mileage: Float
  workHours: Float!
  totalCost: Float
  comments: String
}

type MaintenanceResult {
  success: Boolean!
}

type Query {
  maintenanceAsset(number: String!): MaintenanceAsset
  maintenanceAssets: [MaintenanceAsset!]!
  maintenanceAssetsByNo(assetNo: String!): [MaintenanceAsset!]!
}

type Mutation {
  postMaintenance(input: PostMaintenanceInput!): MaintenanceResult!
}
