scalar Date

type User {
  id: ID!
  username: String!
  domain: String!
  license: String!
  name: String!
}

type Defaults {
  job: String
  price: Float
}

type Job {
  number: String!
  site: String!
  dimensions: JobDimensions!
}

type JobDimensions {
  costCenter: String
  entity: String
}

input LoginInput {
  username: String!
  password: String!
}

input DefaultsInput {
  job: String
  price: Float
}

input JobSearchInput {
  status: [String!]
  postingGroup: [String!]
}

input PostItemInput {
  template: String!
  batch: String!
  date: Date!
  entryType: String!
  document: String!
  item: String!
  description: String
  location: String!
  quantity: Float!
  amount: Float!
  weight: Float!
  job: String!
  prodPostingGroup: String
  costCenterCode: String
  entityType: String
}

type Query {
  user: User
  defaults: Defaults!
  jobs(input: JobSearchInput): [Job!]!
}

type Mutation {
  login(input: LoginInput!): User!
  logout: Boolean!
  updateDefaults(input: DefaultsInput!): Defaults!
  postItem(input: PostItemInput!): Boolean!
}